# Generated by Django 5.2 on 2025-06-13 18:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo total acumulado por el sistema de alquileres.', max_digits=15)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saldo del Administrador',
                'verbose_name_plural': 'Saldos del Administrador',
            },
        ),
    ]
