# Generated by Django 5.2 on 2025-06-20 13:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clave de Encriptación',
                'verbose_name_plural': 'Claves de Encriptación',
            },
        ),
        migrations.AlterField(
            model_name='adminbalance',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo total acumulado por el sistema de alquileres.', max_digits=10),
        ),
    ]
