# Generated by Django 5.2 on 2025-05-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.PositiveIntegerField()),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('AUTO', 'Automóvil'), ('CAMIONETA', 'Camioneta'), ('SUV', 'SUV'), ('MOTO', 'Motocicleta')], default='AUTO', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('sucursal_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='sucursales.sucursal')),
            ],
            options={
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
