# Generated by Django 5.2 on 2025-05-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo',
        ),
    ]
