# Generated by Django 5.2 on 2025-06-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_rename_sucursal_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
