# Generated by Django 5.2 on 2025-05-19 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad_personas', models.IntegerField()),
                ('precio_diario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('MANTENIMIENTO', 'En mantenimiento'), ('ALQUILADO', 'Alquilado')], default='DISPONIBLE', max_length=15)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculos.categoria')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.sucursal')),
            ],
        ),
    ]
