# Generated by Django 5.2 on 2025-05-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='foto_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
