# Generated by Django 5.2 on 2025-05-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculo_foto_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='politica_de_reembolso',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('100', '100%')], default='0', max_length=3),
        ),
    ]
