# Generated by Django 5.2 on 2025-06-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehiculo_politica_de_reembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad',
            field=models.PositiveIntegerField(default=5, help_text='Número de pasajeros'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('SEDAN', 'Sedán'), ('SUV', 'SUV'), ('PICKUP', 'Pickup'), ('VAN', 'Van'), ('DEPORTIVO', 'Deportivo'), ('COMPACTO', 'Compacto')], default='SEDAN', max_length=20),
        ),
    ]
