# Generated by Django 5.2 on 2025-06-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_update_vehicle_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('AUTOMOVIL', 'Automóvil'), ('CAMIONETA', 'Camioneta'), ('4X4', '4x4')], default='AUTOMOVIL', max_length=20),
        ),
    ]
