# Generated by Django 5.2 on 2025-06-13 18:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_alter_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precio_por_dia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio de alquiler por día.', max_digits=10),
        ),
    ]
