# Generated by Django 5.2 on 2025-06-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_alter_vehiculo_precio_por_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.PositiveIntegerField(default=0, help_text='Kilometraje del vehículo'),
        ),
    ]
