# Generated by Django 5.2 on 2025-06-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_vehiculo_kilometraje'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('BAJA', 'Dado de baja')], default='DISPONIBLE', max_length=20, verbose_name='Estado actual'),
        ),
    ]
