# Generated by Django 5.2 on 2025-06-02 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=100)),
                ('ultimos_4_digitos', models.CharField(max_length=4)),
                ('mes_vencimiento', models.PositiveIntegerField()),
                ('ano_vencimiento', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('numero_encriptado', models.TextField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_guardada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarjeta Guardada',
                'verbose_name_plural': 'Tarjetas Guardadas',
            },
        ),
    ]
