# Generated by Django 5.2 on 2025-05-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_direccion_remove_usuario_telefono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='dni',
            new_name='DNI',
        ),
    ]
