# Generated by Django 5.2 on 2025-06-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_estado_pago_reserva_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='conductor_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='conductor_dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='conductor_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
