# Generated by Django 5.2 on 2025-06-14 00:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_conductor_apellido_reserva_conductor_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='conductor_apellido',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='conductor_dni',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='conductor_nombre',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado_pago',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='referencia_pago',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='ultimos_4_digitos_tarjeta',
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_a_reembolsar',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Monto calculado a reembolsar en caso de cancelación.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio total de la reserva.', max_digits=10),
        ),
    ]
