# Generated by Django 5.2 on 2025-06-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_conductor_apellido_reserva_conductor_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='conductor_adicional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='conductor_adicional_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='conductor_adicional_dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='conductor_adicional_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='seguro_por_danos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='silla_para_ninos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='telepass',
            field=models.BooleanField(default=False),
        ),
    ]
