# Generated by Django 5.2 on 2025-06-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_reorganizar_campos_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='costo_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo base de la reserva sin adicionales.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo total de la reserva incluyendo adicionales.', max_digits=10, null=True),
        ),
    ]
