# Generated by Django 5.2 on 2025-06-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_alter_reserva_costo_base_alter_reserva_costo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='conductor_adicional_dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
