# Generated by Django 5.2 on 2025-06-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_alter_reserva_conductor_adicional_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('RETIRADO', 'Retirado'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20),
        ),
    ]
